name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
      - name: Delete old backend docker container
        run: sudo docker rm -f cicd-pipeline-backend-container-test-together || true
      - name: Delete old frontend docker container
        run: sudo docker rm -f cicd-pipeline-frontend-container-test-together || true
      - name: Delete all docker image
        run: sudo docker image prune -a -f

      - name: Pull backend docker image
        run: sudo docker pull gyarmatiadam/cicd-pipeline-backend-test-together:latest
      - name: Run backend docker container
        run: sudo docker run -d -p 9000:9000 --name cicd-pipeline-backend-container-test-together gyarmatiadam/cicd-pipeline-backend-test-together

      - name: Pull frontend docker image
        run: sudo docker pull gyarmatiadam/cicd-pipeline-frontend-test-together:latest
      - name: Run frontend docker container
        run: sudo docker run -d -p 80:80 --name cicd-pipeline-frontend-container-test-together gyarmatiadam/cicd-pipeline-frontend-test-together
        #        run: sudo docker run -d -p 4200:4200 --name cicd-pipeline-frontend-container-test-together gyarmatiadam/cicd-pipeline-frontend-test-together
        #        run: sudo docker run -d -p 4200:4200 -v /Users/gyarmatiadam/Desktop/nginx_config:/etc/nginx/conf.d --name cicd-pipeline-frontend-container-test-together gyarmatiadam/cicd-pipeline-frontend-test-together
        # run: sudo docker run -d -p 4200:4200 -v /home/ubuntu/nginx_config:/etc/nginx/conf.d --name cicd-pipeline-frontend-container-test-together gyarmatiadam/cicd-pipeline-frontend-test-together